name: aro_client
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  window_manager: ^0.3.7

  ffi: ^2.0.0
  webview_flutter: ^4.7.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  webview_flutter_wkwebview: ^3.23.5
  logger: ^2.4.0
  flutter_inappwebview: ^6.1.5
  tray_manager: ^0.5.2
  path: ^1.9.1
  archive: ^3.6.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  path: ^1.9.1 # Use a compatible version of the path package

flutter:
  uses-material-design: true
  generate: true

  assets:
    # - lib/assets/app_icon.png
    # - lib/assets/app_icon_1024.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/app_icon_1024.png"
  macos:
    generate: true
    image_path: "lib/assets/app_icon_1024.png"
  windows:
    generate: true
    image_path: "lib/assets/app_icon_1024.png"
    icon_size: 48
